== Rudder: Continuous configuration for effective compliance

Rudder is an easy to use, web-driven, role-based solution for IT Infrastructure Automation & Compliance.
 
See: https://rudder-project.org for more information on Rudder.

See: https://www.vagrantup.com for more information on vagrant.

This repository contains a Vagrant configuration, enabling
the user to launch from scratch a complete Rudder environment in a few minutes.

=== Synopsis

* Have vagrant >=1.4 and VirtualBox, and run:

----
vagrant up
----

* Connect to https://localhost:8081/ 
* Login with: admin / admin

=== Requirements

There are two dependencies: VirtualBox and Vagrant.

The former may be installed using your favorite package management system, and the latter should be downloaded from vagrant website.

See the complete installation instructions here:

* VirtualBox: https://www.virtualbox.org/wiki/Downloads
* Vagrant: https://www.vagrantup.com/downloads.html 

=== Usage

When you have the required dependencies, clone this repository:

----
git clone https://github.com/Normation/rudder-vagrant.git && cd rudder-vagrant
----

Then you can use the Vagrant environment at will:

* To launch a complete environment (based on latest Ubuntu LTS)

----
vagrant up
----

NOTE: Your Rudder environment is available at: https://localhost:8081/

NOTE: The node and the server are automatically set to communicate with each other.
The node must be accepted in the interface to be fully ready.

=== Command reference for Vagrant

* Launch selectively one machine:

----
vagrant up server
----

* Cleanly shutdown the VMs (issuing a "vagrant up" after that does not deploy the
VMs again but instead starts them normally)

----
vagrant halt
----

* Trash the enviroment (obliterate the VMs)

----
vagrant destroy
----

* Open an SSH shell connection to a machine

----
vagrant ssh server
----

=== Authors

Supported by Normation http://normation.com

The list of contributors is available in https://github.com/Normation/rudder/graphs/contributors

=== License

This project is licensed under GPLv3 license, 
see the provided "LICENSE" file or 
http://www.gnu.org/licenses/gpl-3.0.txt

=== Contributing

Thank you for your interest in our project!
The contribution process is detailed here: 
https://www.rudder.io/en/expand/contribute/

Rudder website: https://www.rudder.io/en/

