= Rudder: Continuous Auditing & Configuration

Rudder is a configuration and security automation platform. Manage your Cloud, hybrid or
on-premises infrastructure in a simple, scalable and dynamic way.

See our https://www.rudder.io[website] for more information about Rudder.

This repository contains a Vagrant configuration, enabling
you to launch from scratch a complete Rudder environment in a few minutes.

== Synopsis

* Have vagrant and VirtualBox installed, and run:

----
vagrant up
----

* Connect to https://localhost:8081/ 
* Login with: admin / admin

== Requirements

There are two dependencies: VirtualBox and Vagrant.

On Linux systems both should be available from your distribution's repository.
See the complete installation instructions for other platforms here:

* https://www.virtualbox.org/wiki/Downloads[VirtualBox]
* https://www.vagrantup.com/downloads.html[Vagrant]

== Usage

When you have the required dependencies, clone this repository:

----
git clone https://github.com/Normation/rudder-vagrant.git && cd rudder-vagrant
----

Then you can use the Vagrant environment at will:

* To launch a complete environment (based on latest Ubuntu LTS)

----
vagrant up
----

NOTE: Your Rudder environment is available at: https://localhost:8081/

NOTE: The node and the server are automatically set to communicate with each other.
The node must be accepted in the interface to be fully ready.

=== Command reference for Vagrant

* Launch selectively one machine:

----
vagrant up server
----

* Cleanly shutdown the VMs (issuing a "vagrant up" after that does not deploy the
VMs again but instead starts them normally)

----
vagrant halt
----

* Trash the environment (obliterate the VMs)

----
vagrant destroy
----

* Open an SSH shell connection to a machine

----
vagrant ssh server
----

== License

This project is licensed under GPLv3 license, see the provided https://github.com/Normation/rudder-vagrant/blob/master/LICENSE[LICENSE] (or
its http://www.gnu.org/licenses/gpl-3.0.txt[source]).
